### PR TITLE
updated old unit-tests

### PR DESCRIPTION
**Pull request by johngitmagnussson**
mostly updated descriptions to say which functions have unit-tests and which don't

### CODE REVIEW

**Review by manimasa — APPROVED** [review]
Apart from the comments being updated i can see some newly added tests. If all tests passed then this can be merged.

**Review by periksso — APPROVED** [review]
new commits ok

**Comment by periksso** [comment]
new commits ok

**Review by periksso — APPROVED** [review]
new commits ok

**Review by periksso — APPROVED** [review]
new commits ok

**Review by periksso — APPROVED** [review]
new commits ok

**Review by periksso — APPROVED** [review]
new commits ok

**Comment by johngitmagnussson** [comment]
pull request does not accept that the merge has happened and been approved, closing this one manually

**Pull request closed without merging**
